spring:
  application:
    name: EurekaServer

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    healthcheck:
                enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/